//
//  font_a.h
//  helloC
//
//  Created by Tasso (Ich) on 03.07.14.
//  Copyright (c) 2014 Tasso (Ich). All rights reserved.
//

#ifndef helloC_font_a_h
#define helloC_font_a_h





//
//  ####_font.h
//  helloC
//
//  Source File: pipstats.tiff
//  Source Path: /Users/luckydonald/Documents/Uni/java-workspace/Image Importer/images/PipBoy/pipstats.png
//
//  Generated by luckydonald on 13.06.14 18:24:25.
//  Copyright (c) 2014 luckydonald. All rights reserved.
//  luckydonald@flutterb.at
//
//
///Copy Pasta Easy Mode (TM) Stuff:

//

#ifndef ####_font_h
#define ####_font_h


typedef unsigned char byte;

#define false   0
#define true    1
#define boolean int

#define ####_FONT_FIRST_CHAR    32
#define ####_FONT_LAST_CHAR     126
#define ####_FONT_HAS_ALPHA     true

//Array with 4 fields per char, (w,h, t,b) _W_idth and _H_eigth of the char start (_T_op) offset and end (_B_ottom) offset, containing the number of left out pixels before the char started with some color.
int ####_font_data[chars*2] {
    1,2, 3,4,   1,2, 3,4,   1,3, 1,3
}
// 846180 Array with 1 fields per Pixel, in total 152280 entries. The encoding uses segments of 1 element representing the Alpha value.
byte ####_font_data[char.each.width * char.each.height] = {
    0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00, //Letter 1
    0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,
    
    0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,
    0x00,0x00,0x00,0x00,


};

#endif